/*
 * File: app/controller/MyBoosController.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LoginRegister.controller.MyBoosController', {
    extend: 'Ext.app.Controller',

    laFuncion: function() {
        alert('ejecutando funcion de controller ext simple');
        //query returns an array of matching components, we choose the one and only
        //console.warn(this.getMainViewView());
        //var test2View = this.getMainViewView();//Ext.ComponentQuery.query('MainView')[0];
        //test2View.abrirLogin();

        //console.warn(LoginRegister.app.views);
        //console.warn(Ext.ComponentQuery.query('Login'));

        //Ext.widget('mainview').abrirLogin();
    },

    laFuncion2: function() {
        Ext.Msg.alert('Alerta', 'Ejecutando funcion laFuncion2');
    },

    laFuncion3: function(msg) {
        Ext.Msg.alert('Mensaje', '::'+msg);
    },

    abrirLogin: function() {
        //Ext.widget('mainview').abrirLogin();
        LoginRegister.app.getVistaPpal().abrirLogin();
    },

    abrirRegistro: function() {
        //Ext.widget('mainview').abrirRegistro();
        LoginRegister.app.getVistaPpal().abrirRegistro();
    },

    cambiarBoton: function() {
        //Ext.widget('mainview').cambiarBoton();
        LoginRegister.app.getVistaPpal().cambiarBoton();
    }

});
