/*
 * File: app/view/MainViewViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LoginRegister.view.MainViewViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mainview',

    moveSlider: function(value, direction) {
        if(this.getView().rendered){
            var svg = document.getElementById("circle-svg");
            var svgDoc = svg.contentDocument;
            var circle = svgDoc.getElementById("my-circle");
            circle.setAttributeNS(null, "c" + direction, value * 5);
        }
    },

    onLoginButtonClick: function(button, e, eOpts) {
        this.getView().abrirLogin();
    },

    onRegisterButtonClick: function(button, e, eOpts) {
        var refs = this.getReferences();

        // Create new login form window
        var register = Ext.create('widget.registerform', {
            loginPanel: refs.loginPanel,
            lougoutPanel: refs.logoutPanel
        });

        // Show window
        register.show();
    },

    onLogoutButtonClick: function(button, e, eOpts) {

    },

    onButton1Click: function(button, e, eOpts) {
        //console.warn(Ext.ComponentQuery.query('LoginForm'));
        //console.warn();
        //Ext.widget('mainview').abrirLogin();
        //var test2View = Ext.ComponentQuery.query('MainView')[0];
        //test2View.abrirLogin();
    },

    onSliderXChange: function(slider, newValue, thumb, type, eOpts) {
        //console.log('Val X:'+newValue);
        this.moveSlider(newValue, 'x');
    },

    onSliderYChange: function(slider, newValue, thumb, type, eOpts) {
        //console.log('Val Y:'+newValue);
        this.moveSlider(newValue, 'y');
    },

    onViewportAfterRender: function(component, eOpts) {
        LoginRegister.app.setVistaPpal(this.getView());
    }

});
