/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LoginRegister.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'LoginRegister.view.MainViewViewModel',
        'LoginRegister.view.MainViewViewController',
        'Ext.panel.Panel',
        'Ext.button.Button',
        'Ext.form.Label'
    ],

    controller: 'mainview',
    viewModel: {
        type: 'mainview'
    },
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'north',
            height: 100,
            title: 'Header',
            dockedItems: [
                {
                    xtype: 'panel',
                    reference: 'loginPanel',
                    dock: 'right',
                    items: [
                        {
                            xtype: 'button',
                            margin: 6,
                            text: 'Login',
                            listeners: {
                                click: 'onLoginButtonClick'
                            }
                        },
                        {
                            xtype: 'button',
                            margin: 5,
                            text: 'Register',
                            listeners: {
                                click: 'onRegisterButtonClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    reference: 'logoutPanel',
                    dock: 'right',
                    hidden: true,
                    items: [
                        {
                            xtype: 'button',
                            margin: 6,
                            text: 'Logout',
                            listeners: {
                                click: 'onLogoutButtonClick'
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'button',
                    text: 'MyButton',
                    listeners: {
                        click: 'onButton1Click'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'btnCambiante',
                    width: 284,
                    text: 'MyButton Cambiante'
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'center',
            itemId: 'contentPanel',
            layout: 'fit',
            title: 'Content',
            items: [
                {
                    xtype: 'label',
                    height: 700,
                    html: '<object style="height:670px; width:900px" data="data/demo2.svg" type="image/svg+xml">     No soporta SVG   </object>',
                    width: 500
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onViewportAfterRender'
    },

    abrirLogin: function() {
        var refs = this.getReferences();

        // Create new login form window
        var login = Ext.create('widget.loginform', {
            loginPanel: refs.loginPanel,
            logoutPanel: refs.logoutPanel
        });

        // Show window
        login.show();
    },

    abrirRegistro: function() {
        var refs = this.getReferences();

        // Create new login form window
        var register = Ext.create('widget.registerform', {
            loginPanel: refs.loginPanel,
            lougoutPanel: refs.logoutPanel
        });

        // Show window
        register.show();
    },

    cambiarBoton: function() {
        try{
            console.info('Llegando con: '+new Date());
            this.down('#btnCambiante').setText(new Date()+'');
        }catch(ex){
            console.error(ex);
        }
    }

});